version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: pg-api
    volumes:
      - ./scripts:/scripts
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-api}
    ports:
      - "${DB_PORT:-5432}:5432"
